spring.application.name=MidsAutomate
server.port=8088

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
spring.datasource.username=MIDSAUTO
spring.datasource.password=MIDSAUTO
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true
#spring.cloud.gateway.routes[0].id=example-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0]=Path=/example/**
#spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
jwt.secret=jakj093e0imdks dpasmfpaskf pkas aksdlas d
logging.level.org.springframework.security=DEBUG

# Debug
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.boot.autoconfigure=DEBUG

# Disable default error handling
server.error.whitelabel.enabled=false
tomcat.util.scan.StandardJarScanFilter.jarsToSkip=*



# Force clean initialization
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
spring.web.resources.static-locations=classpath:/static
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true
logging.level.org.springframework.web=DEBUG
selenium.appUrl=http://localhost:6086/
app.url=http://localhost:6068/
system.driver=windows

#drive path
#window.driver.path=C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\ROOT\\WEB-INF\\classes\\drivers\\chromedriver.exe
window.driver.path=D:\\seleniumTesting\\SeleniumDismantleTesting\\driver\\geckodriver.exe
window.browser.binary=C:\\Users\\Kartik Lohate\\AppData\\Local\\Mozilla Firefox\\firefox.exe


linux.driver.path=/product/user/Root/classes/drivers/chromedriver
linux.browser.binary=
#download directory path
file.upload-dir=C:\Users\Bhanu
img.path=D:\\Testing_Images
download.path=C:\\Users\\Bhanu\\Downloads
opt.required=false

mids.project.url=http://localhost:6068/login