spring.application.name=testing
server.port=8088

window.driver.path=D:\\automationdrivers\\drivers\\geckodriver.exe
window.browser.binary=C:\\Program Files\\Mozilla Firefox\\firefox.exe
project.app.url=https://mids-test.airtel.com/

spring.main.banner-mode=console
spring.banner.location=classpath:banner.txt

