package com.automation.testing.enums;

public enum Department {

	// ADMIN USER
	CIRCLE_MW_PLANNER("CIRCLE MW PLANNER"), CIRCLE_OPERATION_TEAM("CIRCLE OPERATION TEAM"),
	CIRCLE_DEPLOYMENT_TEAM("CIRCLE DEPLOYMENT TEAM"), CIRCLE_MS_PARTNER("CIRCLE MS PARTNER"),
	CIRCLE_DINC_PARTNER("CIRCLE DINC PARTNER"),
	CIRCLE_FTTH_TEAM("CIRCLE FTTH TEAM"),
	
	// USERS
	MW_PLANNER_USER("MW PLANNER USER"), DEPLOYMENT_USER("DEPLOYMENT USER"),
	DINC_PARTNER_USER("DINC PARTNER USER"),OPERATION_USER("OPERATION USER"),
	MS_PARTNER_USER("MS PARTNER USER");

	private final String name;

	Department(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

}
