package com.automation.testing.enums;

import com.automation.testing.interfaces.CommanProcessName;

public enum ProcessName implements CommanProcessName {

	DOWNLOAD_DPR_REPORT, DOWNLOAD_MW_LB_REPORT, DOWNLOAD_UBR_LB_REPORT, DOWNLOAD_PLAN_TRACKING_REPORT,
	DOWNLOAD_DEPLOYMENT_ASSIGNMENT_REPORT, DOWNLOAD_PRI_ISSUE_HISTORY_REPORT, DOWNLOAD_ASSIGNMENT_REPORT,
	DOWNLOAD_SMAPLE_FILE,COUNT_VERIFICATION,

	OPEN_PLAN_TRACKING_REPORT, OPEN_MW_LB_REPORT, OPEN_UBR_LB_REPORT, OPEN_DPR_REPORT,
	OPEN_DEPLOYMENT_ASSIGNMENT_REPORT, OPEN_PRI_ISSUE_HISTORY_REPORT, OPEN_ASSIGNMENT_REPORT,

	LB_PLAN_UPLOAD, OPEN_DPR_PLAN, CIRCLE_SELECT,

	DPR_PLAN_EXECUTION, USER_LOGIN, PLAN_UPLOADED, SR_TO_RFAI_PENDING, MO_PENDING, INSTALL_AND_COMM_PENDING, AT_RAISE,
	AT_ACCEPT, TS_COMPLETE, TOCO_VENDOR,

	SELECT_CIRCLE, PLAN_UPLOAD, TEST_STATUS, OPEN_LB_UPLOAD_PAGE, VERIFY_BULK_UPLOAD_INVALID_ATTRIBUTES,
	VERIFY_PLAN_STATUS,

	OPEN_ERICSSON_AT, DOWNLOAD_ERICSSON_AT, OPEN_NOKIA_AT, DOWNLOAD_NOKIA_AT, DOWNLOAD_CERAGON_AT, OPEN_CERAGON_AT,
	OPEN_AVIAT_AT, DOWNLOAD_AVIAT_AT, DOWNLOAD_HUAWEI_AT, OPEN_HUAWEI_AT,

	STATUS_VERIFY, DATA_FILLED, PAGES,

	SOFT_AT_BULK_UPLOAD, OPEN_SOFT_AT_UPLOAD_PAGE, UPLOAD_AVAIT_SHEET, UPLOAD_NOKIA_SHEET, UPLOAD_CERAGON_SHEET,
	UPLOAD_ERICSSON_SHEET, UPLOAD_HUAWEI_SHEET, VERIFY_SOFT_AT_DATA

	, OPEN_AT_RAISE_PAGE, OPEN_AT_ACCEPT_PAGE, LB_ATTRIBUTE_SET_A, LB_ATTRIBUTE_SET_B, LB_ATTRIBUTE_SET_C,
	LB_ATTRIBUTE_SET_D, LB_ATTRIBUTE_SET_E, UPLOAD_COUNT_VERIFY, LB_ATTRIBUTE_SET_F, LB_ATTRIBUTE_SET_G,
	LB_ATTRIBUTE_SET_CIRCLE, BULK_REVISION, BULK_REVISION_ATTRIBUTE_VALIDATIONS, BULK_REVISION_LB_TEST,

	PLANNER_ASSIGNMENT, OPERATION_ASSIGNMENT, DINC_ASSIGNMENT, MS_ASSIGNMENT, DEPLOYMENT_ASSIGNMENT,

	REQUEST_FOR_CANCELLATION, CANCEL_THE_PLAN, REVIEW_THE_PLAN, REVISED_PLAN,

	BULK_ASSIGNMENT, BULK_UPLOAD_FOR_SOFT_UPGRADE, BULK_CANCELLATION,

	POP_INFO_PAGE, RFC_REPORT, NEP_DISMANTLE_LINK_REPORT, DISMANTLE_MATERIAL_STATUE, MIDS_DPR_UPLOAD,
	FREQUENCY_DETAIL_REPORT, CHANGE_ASSIGN_USER,

	VERIFY_PHY_AT, PHY_AT_VALUE_FILLING, VERIFY_FIELDS_VALUES, BULK_UPLOAD_WITH_VALID_DATA

	;

	@Override
	public String getValue(CommanProcessName processName) {
		// TODO Auto-generated method stub
		return name();
	}

}
