package com.automation.testing.enums;

import com.automation.testing.interfaces.CommanProcessName;

public enum TrafficServiceName implements CommanProcessName{

	USER_LOGIN,

	TRAFFIC_UPLOAD, OPEN_TRAFFIC_REPORT, DOWNLOAD_TRAFFIC_REPORT, OPEN_TRAFFIC_TRACK_VIEW,
	DOWNLOAD_TRAFFIC_TRACK_REPORT, DOWNLOAD_TRAFFIC_SHIFTING_DELETION, DOWNLOAD_TRAFFIC_TRACK_VIEW,

	OPEN_TRAFFIC_ASSIGNMENT_HISTORY, DOWNLOAD_TRAFFIC_ASSIGNMENT_HISTORY, OPEN_TRAFFIC_SHIFTING_DELETION,

	TS_PLAN_VERIFICATION, TS_SHEET_UPLOAD, PLAN_HOLD, PLAN_CANCEL, PLAN_RESOLVE, VERIFY_TS_STATUS_FIELD,
	VERIFY_HOLD_AND_CANCEL, VERIFY_TS_DONE,

	BASIC_TS_VALIDATION, DNC_VALIDATIONS, TS_2G_VALIDATIONS, TS_4G_VALIDATIONS, TS_5G_VALIDATIONS,
	
	BULK_ASSIGNMENT, PLAN_CANCELLATION, BULK_REOPEN, PLAN_DELETE, HOLD_RETRIEVE, HOLD_UPDATE_STATUS,
	NAVIGATE_TS_TARCK_VIEW;

	@Override
	public String getValue(CommanProcessName processName) {
		// TODO Auto-generated method stub
		return name();
	}

}
