package com.automation.testing.interfaces;

public interface ReportConstants {
	String LB_REPORT = "LB_REPORT";
	String MIDS_DPR = "MIDS_DPR";
	String MW_PLAN_TRACKING = "MW_PLAN_TRACKING";
	String PRI_ISSUE_DATA = "PRI_ISSUE_DATA_REPORT";
	String UBR_REPORT = "UBR Report";
	
	String ASSIGNMENT_HISTORY = "ASSIGNMENT_HISTORY_REPORT";
	String DEPLOYMENT_ASSIGNMENT_HISTORY = "DEPLOYMENT_ASSIGNMENT_HISTORY_REPORT";

	String AVIAT_AT = "AVIAT_SOFT_AT_REPORT";
	String CERAGON_AT = "CERAGON_AT_REPORT";
	String ERICSSON_AT = "ERICSSON_AT_REPORT";
	String HUAWEI_AT = "HUAWEI_AT_REPORT";
	String NOKIA_AT = "NOKIA_SOFT_AT_REPORT";
}
